apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ls-secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ls-secrets.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.persistence.enabled }}
  {{- if eq .Values.global.persistence.type "s3" }}
    {{- if .Values.global.persistence.config.s3.accessKey }}
  storage-aws-access-key-id: {{ .Values.global.persistence.config.s3.accessKey | toString | b64enc | quote }}
    {{- end }}
    {{- if .Values.global.persistence.config.s3.secretKey }}
  storage-aws-secret-access-key: {{ .Values.global.persistence.config.s3.secretKey | toString | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.global.persistence.type "azure" }}
    {{- if .Values.global.persistence.config.azure.storageAccountName }}
  storage-azure-account-name: {{ .Values.global.persistence.config.azure.storageAccountName | toString | b64enc | quote }}
    {{- end }}
    {{- if .Values.global.persistence.config.azure.storageAccountKey }}
  storage-azure-account-key: {{ .Values.global.persistence.config.azure.storageAccountKey | toString | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.global.persistence.type "gcs" }}
    {{- if .Values.global.persistence.config.gcs.applicationCredentialsJSON }}
  key.json: {{ .Values.global.persistence.config.gcs.applicationCredentialsJSON | toString | b64enc | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
