apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lse-app.fullname" . }}
  labels:
    {{- include "lse-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "lse-app.selectorLabels" . | nindent 6 }}
  {{- with .Values.app.deploymentStrategy }}
  strategy:
  {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.app.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lse-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lse-app.serviceAccountName" . }}
      initContainers:
        - name: lse-db-migrations
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          command: [ "python3", "/label-studio-enterprise/label_studio_enterprise/manage.py", "migrate" ]
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            {{ template "lse.common.envs" . }}
            - name: INIT_CONTAINER
              value: "true"
            {{- if .Values.app.logLevel }}
            - name: LOG_LEVEL
              value: "{{ .Values.app.logLevel }}"
            {{- end }}
            {{- if .Values.app.debug }}
            - name: DEBUG
              value: "true"
            {{- end }}
      containers:
        - name: lse-app
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          workingDir: /label-studio-enterprise
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            {{ template "lse.common.envs" . }}
            {{- if .Values.app.logLevel }}
            - name: LOG_LEVEL
              value: "{{ .Values.app.logLevel }}"
            {{- end }}
            {{- if .Values.app.debug }}
            - name: DEBUG
              value: "true"
            {{- end }}
            {{- if .Values.app.extraEnvironmentVars -}}
            {{- range $key, $value := .Values.app.extraEnvironmentVars }}
            - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.app.extraEnvironmentSecrets -}}
            {{- range $key, $value := .Values.app.extraEnvironmentSecrets }}
            - name: {{ printf "%s" $key | replace "." "_" | upper | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.secretKey }}
            {{- end }}
            {{- end }}
          ports:
            - name: {{ .Values.app.service.portName }}
              containerPort: 8085
              protocol: TCP
          {{- if .Values.app.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: "{{ default "" .Values.global.contextPath }}{{ .Values.app.readinessProbe.path }}"
              port: 8085
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.app.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.app.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: "{{ default "" .Values.global.contextPath }}{{ .Values.app.livenessProbe.path }}"
              port: 8085
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.app.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
          {{- end }}
          lifecycle:
            preStop:
              exec:
                command: ['/bin/sh', '-c', 'sleep 15']
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
