apiVersion: v1
kind: Service
metadata:
  name: {{ include "lse-app.fullname" . }}
  labels:
    {{- include "lse-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: {{ .Values.app.service.portName }}
  selector:
    {{- include "lse-app.selectorLabels" . | nindent 4 }}
