{{- if .Values.rqworker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lse-rqworker.serviceAccountName" . }}
  labels:
    {{- include "lse-rqworker.labels" . | nindent 4 }}
  {{- with .Values.rqworker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
