{{- if .Values.app.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ls-app.fullname" . }}-role
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ls-app.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - nonroot
    resources:
      - securitycontextconstraints
    verbs:
      - use
  {{- if .Values.app.rbac.rules -}}
    {{- toYaml .Values.app.rbac.rules | nindent 2 }}
  {{- end }}
{{- end }}
