{{- if .Values.app.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ls-app.serviceAccountName" . }}
  labels:
    {{- include "ls-app.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.app.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
