{{- if and .Values.enterprise.enabled .Values.rqcron.enabled -}}
{{- if .Values.rqcron.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ls-rqcron.serviceAccountName" . }}
  labels:
    {{- include "ls-rqcron.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.rqcron.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
