{{- if and .Values.enterprise.enabled .Values.rqworker.enabled -}}
{{- if .Values.rqworker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ls-rqworker.serviceAccountName" . }}
  labels:
    {{- include "ls-rqworker.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.rqworker.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}