{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ls-app.fullname" . }}
  labels:
    {{- include "ls-app.labels" . | nindent 4 }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.metrics.serviceMonitor.jobLabel | quote }}
  selector:
    matchLabels:
      {{- include "ls-app.selectorLabels" . | nindent 6 }}
      {{- if .Values.metrics.serviceMonitor.selector }}
      {{- include "tplvalues.render" (dict "value" .Values.metrics.serviceMonitor.selector "context" $) | nindent 6 }}
      {{- end }}
  endpoints:
    {{- if .Values.metrics.uwsgiExporter.enabled }}
    - path: /metrics
      port: uwsgimetrics
    {{- end }}
    - path: /metrics
      port: djangometrics
  {{- if .Values.metrics.serviceMonitor.interval }}
  interval: {{ .Values.metrics.serviceMonitor.interval }}
  {{- end }}
  {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
  scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
  {{- end }}
  {{- if .Values.metrics.serviceMonitor.honorLabels }}
  honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
  {{- end }}
  {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
  metricRelabelings: {{- include "tplvalues.render" ( dict "value" .Values.metrics.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
  {{- end }}
  {{- if .Values.metrics.serviceMonitor.relabelings }}
  relabelings: {{- include "tplvalues.render" ( dict "value" .Values.metrics.serviceMonitor.relabelings "context" $) | nindent 8 }}
  {{- end }}
{{- end }}
