apiVersion: v2
name: label-studio
description: Label Studio is a data labeling tool
home: https://labelstud.io/
type: application
icon: https://raw.githubusercontent.com/heartexlabs/label-studio/master/images/logo.png
# Chart version
version: 1.11.2
# Label Studio release version
appVersion: "1.20.0"
kubeVersion: ">= 1.14.0-0"
dependencies:
  - name: redis
    version: "21.2.14"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: postgresql
    version: "16.7.24"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
